# Function to add sine and cosine terms to a weekly timeseries for fitting seasonal terms in a glm
# input ts a tibble with a weekly timeseries
create_season_data <- function(ts) {
  ts_len <- nrow(ts)
  sin_cos <- data.frame(
    sin = sin(2 * pi * (1:ts_len) / 52),
    cos = cos(2 * pi * (1:ts_len) / 52)
  )
  ts %>% bind_cols(sin_cos)
}

# Function to plot a timeseries with or without signals generated by an outbreak detection algorithm
# If results from outbreak detection are also shown setting with_signals = TRUE the expectation, threshold and signals are  visulised. Furthermore the Signal Detection weeks and Training data are marked.
# input parameter ts tibble with weekly timeseries data consisting of a variable date and cases if with_signals = FALSE, for with_signals = TRUE a column with threshold and expectation is required in addition
# input parameter with_signals boolean specifying whether ts contains signal results
plot_ts <- function(ts, with_signals = FALSE) {
  plot <- ggplot(ts, aes(x = date, y = cases)) +
    geom_bar(stat = "identity") +
    theme_bw()

  if (with_signals) {
    # Separate data for bars and lines
    ts_for_lines <- ts

    ts <- ts %>%
      mutate(category = if_else(!is.na(alarms), "Signal Detection weeks", "Training Data"))

    plot <- ggplot() +
      geom_bar(data = ts, aes(x = date, y = cases, fill = category), stat = "identity") +
      geom_line(data = ts_for_lines, aes(x = date, y = threshold, color = "Threshold"), linewidth = 1) +
      geom_line(data = ts_for_lines, aes(x = date, y = expectation, color = "Expectation"), linewidth = 1) +
      {
        if (any(ts$alarms == 1, na.rm = TRUE))
          geom_point(data = filter(ts, alarms == 1), aes(x = date, y = cases, color = "Signals"), shape = 4, size = 2, stroke = 2)
      } +
      labs(color = "") +
      scale_color_manual(values = c("Threshold" = "blue", "Expectation" = "black", "Signals" = "red")) +
      scale_fill_manual(values = c("Signal Detection weeks" = "orange", "Training Data" = "#999")) +
      labs(color = NULL, fill = NULL) + # Removes titles for both color and fill legends
      theme_bw() +
      theme(legend.position = "bottom") +
      guides(
        fill = guide_legend(override.aes = list(shape = NA)) # Order bar legend second
      )
  }
  plot
}
